

/**
 * CommoneReducer
 */
export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS"

/**
 * 分类 action
 */
export const REQUEST_CATEGORY_START = "REQUEST_CATEGORY_START"
export const REQUEST_CATEGORY_SUCCESSS = "REQUEST_CATEGORY_SUCCESSS"
export const REQUEST_CATEGORY_FAILURE = "REQUEST_CATEGORY_FAILURE"
 